### ISSUE TITLE
Prática 1 - GitHub Issues

### ISSUE THREAD

**Issue by IzavanCorreia** [IzavanCorreia/GCMS-Izavan-Correia#1]
Seja Bem-vindo, por favor adicione seu nome no documento no formato Markdown do link abaixo!!
[README](https://github.com/IzavanCorreia/GCMS-Izavan-Correia/blob/main/README.md)

**Comment by ramidedantas** [comment]
Mudança realizada @IzavanCorreia.

**Comment by IzavanCorreia** [comment]
Certo, muito obrigado!!
